Add service registry
open-rmf/bevy_impulse pull request #27
Opened 2024-10-02 05:48 UTC by koonpeng

## New feature implementation

### Implemented feature

Services can be registered using a new `register_service` method on `App`.

```rs
app.register_service(foo.into_blocking_service());
```
This will automatically get a unique service id and generate json schema definitions of the request and response types. The service registry itself implements `serde::Serialize` so we can easily expose all the registered services to external parties.

### Next steps

The idea would be to implement `IntoServiceBuilder<>` for `ServiceRegistrations`, this will allow us to build a workflow from the serialized form. Mostly likely, all services created from the builder will be some `SerializedService` that wraps the original service and calls it through dynamic dispatch, we should be able to get a function pointer to the original service when we register it.

2025-01-01 12:57 UTC, mxgrey requested changes
This is looking very impressive! I'm leaving some initial feedback on the JSON schema. I'll keep reviewing this PR tomorrow to provide feedback on the implementation.

I'll go on record as saying that I have a strong dislike of JSON's `camelCase` convention in general. That's not a critique of your work here since I know `camelCase` is the most widely accepted convention for naming fields in the JavaScript/JSON ecosystem. I'm only voicing that I'd personally prefer if we use `snake_case` since I find it much more readable. We also have a precedent set in [`rmf_api_msgs` schemas](https://github.com/open-rmf/rmf_api_msgs/blob/0141ab64e03bf08aba79be76b31ea02a55a3b296/rmf_api_msgs/schemas/robot_commission_request.json#L22) but of course I'm the one that set that precedent so that point should be taken with a grain of salt.

I won't make a big fuss about the `camelCase` if you feel strongly that we should use it, but if you're open to using `snake_case` I'd appreciate the consistency and (subjective) readability.

2025-01-01 12:57 UTC, mxgrey commented on diagram.schema.json
> +          "description": "Connects the request to a registered node.\n\n``` # bevy_impulse::Diagram::from_json_str(r#\" { \"ops\": { \"start\": { \"type\": \"start\", \"next\": \"nodeOp\" }, \"nodeOp
I'm curious: Is there an IDE or other tool that renders this description string, and if so what does this string look like when rendered? As raw text I find it difficult to interpret.

2025-01-01 12:57 UTC, mxgrey commented on diagram.schema.json
> +            "nodeId",
I'm a bit reluctant to call this a `nodeId` because
1. Users may think this is supposed to be a UUID rather than an idiomatic name
2. Users may assume every node needs a unique `nodeId`
3. This ID refers to a node **_builder_**, not a node
4. Users may get confused between the purpose of this field and the _name_ of the node (the node's key in the `ops` dictionary)

I would consider using another name for this like `provider` or `builder`.

2025-01-01 12:57 UTC, mxgrey commented on diagram.schema.json
> +          "oneOf": [
We don't need to force users to choose between keys or sequences. I think we can make the split operation look like:

```
{
    "type": "split",
    "keys": {
        # split key -> name of connected node 
        "a": "node_connected_to_a",
        "b": "node_connected_to_b"
    },
    "sequential": [
        "first_node",
        "second_node",
    ]
}
```

The API for split supports both of these kinds of connections simultaneously. `sequential` connections will connect, in sequence, to any split outputs that are not already explicitly connected to by key.

2025-01-01 12:57 UTC, mxgrey commented on diagram.schema.json
> +          "description": "Drops the request, equivalent to a no-op.",
I'm a little bit torn on whether `next` should be strictly required field or whether we should interpret the absence of a `next` as a disposal.

In the Rust API we issue a compiler warning if the user lets an output drop without explicitly saying they want to dispose it because it's easy for users to overlook a dropped value that they didn't mean to drop. But I don't think the json schema is where we should try to sniff out those issues. I think it should primarily be the responsibility of the GUI which we will eventually provide for generating these files.

With that in mind, I think the role of the schema should be to help the GUI communicate the user's intention to the executor. What if we change the schema to look like this:

```json
{
    "type": "node",
    "provider": "mul",
    "dispose_output": true,
}
```

So `next` is not strictly required by the schema, and `"dispose_output": true` can be used to indicate that the user has explicitly asked for the output to be disposed (we can give it a default value of `false`). If `next` is missing **and** `dispose_output` is `false` then the GUI and executor can both issue a warning at runtime.

2025-01-02 06:44 UTC, koonpeng commented on diagram.schema.json
> +          "description": "Connects the request to a registered node.\n\n``` # bevy_impulse::Diagram::from_json_str(r#\" { \"ops\": { \"start\": { \"type\": \"start\", \"next\": \"nodeOp\" }, \"nodeOp
In vscode it will render the the newlines but it doesn't seem to render the markdown, schemars also doesn't seem to generate the formatting properly. I guess we should remove the examples from the schema to make it play nicer.

2025-01-02 09:21 UTC, mxgrey requested changes
These capabilities are looking fantastic, and the implementation is generally very good.

I've left a bunch of inline comments for things that I think could use some tweaking. For larger changes I've opened issues #43 and #44 as follow up items rather than blocking this PR.

2025-01-02 09:29 UTC, koonpeng commented on diagram.schema.json
> +            "nodeId",
ca569172a3e2b1214625b53046be7d95621803ef

2025-01-02 09:32 UTC, mxgrey commented on diagram.schema.json
> +            "nodeId",
Nice, we'll just need to update the [`NodeNotFound`](https://github.com/open-rmf/bevy_impulse/commit/ca569172a3e2b1214625b53046be7d95621803ef#diff-e7190dc1175e279538fa4f9d17a6cbb46119d50677ed0eeea978f26ca17a119bR402) variant to `BuilderNotFound`.

2025-01-02 09:42 UTC, koonpeng commented on diagram.schema.json
> +                "start"
I think if we make next optional with automatic implied `dispose` if not specified, then we can avoid reserving a name for `terminate` as well.

2025-01-02 09:46 UTC, koonpeng commented on src/diagram/generate_schema.rs
> +    let schema = schemars::schema_for!(Diagram);
There is a test to check if they go out of sync. I'm not too sure about adding a `build.rs` as technically you should not create files outside the build directory to avoid messing up the build cache.

2025-01-02 09:52 UTC, koonpeng commented on src/diagram/join.rs
> +                Err(DiagramError::TypeMismatch)
I would like to avoid automatic serialization if possible.

> Otherwise users will only be able to join outputs whose types perfectly match, but I expect in most cases they'll want to join different output types to create one data structure that combines both types.

In that case, they can use the `transform` op to convert it to a compatible type, it does a serialization and a deserialization. But right now the lack of support for serializing joined outputs is stopping the ability to compose something out of multiple outputs.

2025-01-02 09:57 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub(super) id: &'static str,
I think the idea is exactly to disallow generating node builders at run time. The builder id should be consistent and never change. The way it is designed now, it is not possible to generate a builder at run time, builders are callbacks that return a node, to generate a builder at run time would require compiling code.

2025-01-02 09:58 UTC, mxgrey commented on src/diagram/join.rs
> +                Err(DiagramError::TypeMismatch)
I think we can move this conversation to #44, but being able to join multiple different data types is for sure going to be a crucial feature.

2025-01-02 10:32 UTC, mxgrey commented on diagram.schema.json
> +                "start"
I see what you mean but I'd much prefer if `terminate` was explicit somehow due to how significant it is to the workflow.

I'd rather have `"terminate": true` than nothing at all, but I'm a bit concerned about how people would interpret this:

```json
{
    "next": "something",
    "terminate": true
}
```

I suppose we could produce an error for that.

One option could be:

```rust
#[derive(Serialize, Deserialize)]
#[serde(tag = "next")]
enum Next {
    Connect { target: OperationId },
    Terminate,
    Dispose,
}
```

If we use that with `#[serde(flatten)]` on the `next` field then we should get a pattern like this:

```json
{
    "foo": {
        "type": "node",
        "builder": "foo",
        "next": "connect",
        "target": "bar"
    },
    "bar": {
        "type": "node",
        "builder": "bar",
        "next": "terminate"
    }
}
```

However this would add some complexity for things like `fork_clone` and `fork_result`, e.g.:

```json
{
    "foo": {
        "type": "fork_clone",
        "next": [
            { "next": "connect", "target": "fork_result" },
            { "next": "connect", "target": "bar" }
        ]
    },
    "fork_result": {
        "type": "fork_result",
        "ok": {
            "next": "connect",
            "target": "foo"
        },
        "err": {
            "next": "terminate"
        }
    }
}
```

We could forbid `fork_clone` from special connections like terminate or disposing, but that might not work well if some other special operation comes along, such as `stream_out` which I mention in #43.

What if we have an `op:` string prefix for special operations, so the previous example could look like:

```json
{
    "foo": {
        "type": "fork_clone",
        "next": ["fork_result", "bar"]
    },
    "fork_result": {
        "type": "fork_result",
        "ok": "foo",
        "err": "op:terminate"
    }
}
```

Every string beginning with `op:` is considered reserved for builtin operations of `bevy_impulse` so we can add `op:stream_out` and others in the future without any risk of breaking backwards compatibility.

2025-01-02 10:41 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    pub(super) id: &'static str,
We absolutely should not get in the way of generating node builders at runtime. That's an artificial limitation with no benefit that we'd be imposing due to a lack of imagination on our part.

There is no reason that a user shouldn't be allowed to generate a node builder at runtime, especially if the builder doesn't need to register a continuous service. There could be node builders that use closures which capture runtime data which gets streamed in while the application is running. Then the remote client could ask for that specific node builder to be used in a diagram.

2025-01-03 02:18 UTC, koonpeng commented on diagram.schema.json
> +                "start"
I would prefer that we avoid reserving special names because that messes up schema validation. A `oneOf` with any string and some reserved enums would always pass validation even if the op does not exist. Json schema does have a `pattern` that specify a regex that the string must match, but I still prefer to avoid that if possible.

But if we were to reserve names, I think it is better to avoid special characters like `:`, they could cause problems in the future. `_` and `-` would be the safest but less ergonomic.

2025-01-03 02:55 UTC, koonpeng commented on diagram.schema.json
> +            "nodeId",
01d3bb61e3a429374caf2ca9ebde931932c14c71

2025-01-03 03:06 UTC, koonpeng commented on src/diagram.rs
> +impl Display for DiagramError {
a74223c2379ac1feac595ed3deb7f729e9f89295

2025-01-03 03:08 UTC, koonpeng commented on src/diagram/serialization.rs
> +impl Display for SerializationError {
35a1bb741e81f972663c7445d71dccc31628acbc

2025-01-03 03:11 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub fn register_node<Config, Request, Response, Streams: StreamPack>(
f529f5cd1392402115cc319c681a8acb3f5d8c15

2025-01-03 03:40 UTC, koonpeng commented on examples/diagram/calculator/src/main.rs
> +    let mut args = std::env::args();
3cbbd137c922cbe4616ab108a3f481723ffdd4cf

2025-01-03 03:41 UTC, koonpeng commented on examples/diagram/calculator/src/main.rs
> +    app.add_systems(Update, flush_impulses());
3cbbd137c922cbe4616ab108a3f481723ffdd4cf

2025-01-03 03:44 UTC, koonpeng commented on src/diagram.rs
> +    pub fn spawn_workflow<Streams>(
Should we remove `spawn_workflow` instead, and only have `spawn_io_workflow` to keep consistency? Also if/when we support streams, then we will not have naming conflicts.

2025-01-03 03:57 UTC, mxgrey commented on diagram.schema.json
> +                "start"
I believe I've come up with a schema that can satisfy all concerns:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, Hash, PartialEq, Eq, PartialOrd, Ord)]
#[serde(untagged, rename_all = "snake_case")]
pub enum OperationId {
    Target(String),
    Builtin { builtin: BuiltinOperation },
}

/// These operations are built into `bevy_impulse` and therefore do not require
/// the `ops` section to instantiate it.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, Hash, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum BuiltinOperation {
    /// Use the output to terminate the workflow. This will be the return value
    /// of the workflow.
    Terminate,
    /// Dispose of the output.
    Dispose,
}
```

In terms of what the json would look like, we'd get this:

```json
{
    "foo": {
        "type": "fork_clone",
        "next": ["fork_result", "bar"]
    },
    "fork_result": {
        "type": "fork_result",
        "ok": "foo",
        "err": { "builtin": "terminate" }
    },
    "bar": {
        "type": "node",
        "builder": "bar",
        "next": { "builtin": "dispose" }
    }
}
```

Regular strings would just be operation IDs within the `ops` section, whereas `{ "builtin": "x" }` would be for unambiguous builtin operations which are explicitly enumerated and therefore can be validated.

2025-01-03 04:07 UTC, koonpeng commented on src/diagram.rs
> +        app: &mut App,
6d8340f0c372e68fe364062b28221f1ecae5717e

2025-01-03 04:09 UTC, koonpeng commented on src/diagram.rs
> +type DynScope<Streams> = Scope<ScopeStart, ScopeTerminate, Streams>;
6d8340f0c372e68fe364062b28221f1ecae5717e

2025-01-03 04:09 UTC, mxgrey commented on src/diagram.rs
> +    pub fn spawn_workflow<Streams>(
I'm hoping that the absence of stream support will be temporary and that we won't do a release until we get it in. I don't think it will take long to implement, I'm just punting on it for right now since this PR is already very beefy. Once we have stream support, all workflows generated by diagrams should have `DiagramStream` as its stream type, so there would no longer be a need for `spawn_io_workflow`.

That being said, if you're concerned that we could suddenly have a spike in users of the `main` branch in between the time we merge this PR and merge the next one then we could go ahead and keep `spawn_io_workflow` for now and get rid of `spawn_workflow` until streams are supported.

2025-01-03 04:09 UTC, koonpeng commented on src/diagram.rs
> +    /// Drops the request, equivalent to a no-op.
cf121eadc09eb283845fd7ace76aa2c5d5bbe600

2025-01-03 04:09 UTC, koonpeng commented on src/diagram.rs
> +    /// If the request is serializable, transforms it by running it through a [CEL](https://cel.dev/) program.
cf121eadc09eb283845fd7ace76aa2c5d5bbe600

2025-01-03 04:09 UTC, koonpeng commented on src/diagram.rs
> +    /// Waits for an item to be emitted from each of the inputs, then combined the
cf121eadc09eb283845fd7ace76aa2c5d5bbe600

2025-01-03 04:09 UTC, koonpeng commented on src/diagram.rs
> +    /// If the request is a list-like or map-like object, splits it into multiple responses.
cf121eadc09eb283845fd7ace76aa2c5d5bbe600

2025-01-03 04:14 UTC, mxgrey commented on diagram.schema.json
> +          "description": "Drops the request, equivalent to a no-op.",
If we follow through on [this recommendation](https://github.com/open-rmf/bevy_impulse/pull/27#discussion_r1901449661) then we can keep `next` as required and any disposed outputs must be set to `{ "builtin": "dispose" }`.

2025-01-03 04:21 UTC, mxgrey commented on src/diagram.rs
> +    #[error("response cannot be splitted")]
```suggestion
    #[error("response cannot be split")]
```

split is one of those weird English words where it is its own past tense

2025-01-03 04:27 UTC, koonpeng commented on src/diagram.rs
> +    pub fn spawn_workflow<Streams>(
> Once we have stream support, all workflows generated by diagrams should have DiagramStream as its stream type, so there would no longer be a need for spawn_io_workflow.

I think there might be cases where there will be other streams. I see streams as something that does not necessarily need to come from the request to a workflow, an app that uses diagram could have some default/universal stream, in those cases, streams would be opaque as we never have to do any serialization.

2025-01-03 05:15 UTC, koonpeng commented on diagram.schema.json
> +                "start"
I think this looks good :+1:

2025-01-03 05:16 UTC, koonpeng commented on src/diagram/fork_result.rs
> +        assert_eq!(output.type_id, TypeId::of::<Result<T, E>>());
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:16 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub(super) fn into_output<T>(self) -> Output<T>
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:17 UTC, koonpeng commented on src/diagram/join.rs
> +    let first_type = outputs[0].type_id;
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:17 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        InputSlot::<T>::new(self.scope, self.source)
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:17 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        write!(
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:17 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        write!(
c23ffe414d9d60f4f2063ec1fbb39a4ee5c7b906

2025-01-03 05:20 UTC, mxgrey commented on src/diagram.rs
> +    pub fn spawn_workflow<Streams>(
I do have some thoughts on how it may be possible to support other concrete stream types, but it would be related to also supporting concrete request and response types, and it would require some reimplementation of the `Scope` operation. I would save that for a far future PR.

2025-01-03 05:28 UTC, mxgrey commented on src/diagram/join.rs
> +    let first_type = outputs[0].type_id;
We shouldn't allow an empty join, we should treat it as an error. An empty join can never be triggered which makes everything connected to it effectively dead. If a user has an empty join in their diagram then they have made some kind of mistake and we should give them a specific error to let them know.

2025-01-03 05:29 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub(super) id: &'static str,
> I could write an example of a bevy system that could take runtime data from an event and move it into a closure to produce and register a new node builder if you'd like.

I guess it is up for debate whether this would be considered a run time builder or still compile time. Technically there is only 1 closure (assuming no generics at play) that captures runtime values. I guess that there could be some use cases to do this over using configs.

2025-01-03 05:35 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub fn register_node<Config, Request, Response, Streams: StreamPack>(
f529f5c

2025-01-03 05:41 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        name: &'static str,
7a825658dfc12a5e58380e1b54e68ddf7f4e36ee

2025-01-03 05:43 UTC, koonpeng commented on src/diagram.rs
> +    #[error("response cannot be splitted")]
bf63e5b20290473dbc34dc95a1e0057422d8499d

2025-01-03 05:50 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    pub(super) id: &'static str,
It's true that ultimately **_something_** needs to be compiled ahead of time, but there are many ways you could make that **_something_** very dynamic. Here's one example:

```rust
fn create_new_node_builder(
    builder_name: String,
    service: Service<serde_json::Value, serde_json::Value>,
    registry: &mut NodeRegistry,
) {
    registry.register_node_builder(
        builder_name.clone(),
        builder_name.clone(),
        move |builder, config: ()| {
            builder.create_node(service.clone())
        },
    );
}
```

In this case `service` may itself be something generated at runtime, e.g. a workflow which itself gets built from a diagram description. Users might want to register their custom tasks as node builders, and those custom tasks may be stored in databases that need to be loaded at runtime.

2025-01-03 05:52 UTC, mxgrey commented on src/diagram/generate_schema.rs
> +                return Err(String::from("There are changes in the json schema, please run `cargo run -F=diagram generate_schema` to regenerate it"));
We'll go forward with the test approach for now and see how it feels. If we run into friction down the road we can revisit the idea of fully automating the generating.

2025-01-06 03:04 UTC, koonpeng commented on src/diagram/testing.rs
> +            "multiply3_cloneable",
c5ced4519a688c399e9529a91b9ac75a6a895e88

2025-01-06 03:20 UTC, koonpeng commented on src/diagram/transform.rs
> +    let transform_node = builder.create_map_block(
> terminating: CEL programs cannot loop forever;

I saw on the docs that CEL is designed to be terminating https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions. It does reserve words like "loop" and "while" but it seems to be just to avoid conflicts when embedding CEL.

I think in most cases we can assume CEL programs to be short and simple, for complex transformations that can take a long time, the better approach would be to have a node that does the transformation, using native rust code instead of CEL.

2025-01-06 03:24 UTC, mxgrey commented on src/diagram/transform.rs
> +    let transform_node = builder.create_map_block(
Sure, we can go with this as-is, and if we ever do find a use case for long-running CEL operations we can always add an async option in a backwards-compatible way.

2025-01-06 03:29 UTC, mxgrey commented on src/diagram/node_registry.rs
> +        name: &'static str,
It says `name` is used for display purposes, but where does it actually get used?

If it's meant to be displayed in workflow visualizations in the future then I'd suggest the following:
1. Remove this argument from the `register_node_builder` API
2. Support a `"label": "simple name"` in the `"type": "node"` operation

I think it will make more sense for human-readable node names to be decided inside the diagram file than by the `register_node_builder` call. For example if you have multiple instances generated by the same node builder, you may want them to have different human-readable names, which the current API would not support.

2025-01-06 04:36 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
Yeah the reason for this is to support opt-out.

I think there is lots of ways to design this part of the code, I'm inclined to say that we need a long discussion to find the best approach. The "problem" is that refactoring this will likely result in the change of the public api.

Some ideas I had:

* Having some operations like fork clone opt-out, similar to serialization. For now it's just fork clone and fork result I'm considering but with the above design, I find it less ergonomic that this change will require refactoring instead of just flipping a switch.
* A way to reduce the amount of generic params is to group ops together, but that doesn't really reduce the complexity, we would get params like `ForkCloneAndUnzip<NotSupported, DefaultImpl>`.
* Perhaps the most rustic approach would be to use derive macros. Technically serialization is indirectly "opt-in" because you need to derive `JsonSchema` and `Serialize`, so it makes sense to derive an `OpaqueMessage`. But should we extend it to other operations? Something like

```rust
#[derive(DiagramMessage)]
#[diagram_message(serialize = false)
struct Foo {}
```

The downside is that every request and response would need to `derive`, but even with the current approach they most likely need to derive `JsonSchema` and `Serialize` already anyway. I think a huge advantage is that it reduces the occurrence of incomplete flagging, e.g. a `Result<_, _>` not being flagged with `with_fork_result`. It also allows to automatically impl some operations like unzip and fork result https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2be9b765e3346bc29bec6397f224f616.

2025-01-06 04:39 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    pub(super) id: &'static str,
[7a82565](vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

2025-01-06 04:47 UTC, koonpeng commented
The debug print outs are actually intended, I think they will be useful for diagnostics. They won't appear unless the user

1. set ups a tracing emitter
2. turns on debug level tracing

bevy uses the same framework and prints some logs as well

e.g. `RUST_LOG=debug cargo test -F=diagram diagram -- --show-output`
```
...
2025-01-06T04:44:56.577813Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 10v2
2025-01-06T04:44:56.577870Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 26v0
2025-01-06T04:44:56.577918Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 9v1
2025-01-06T04:44:56.577959Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 29v0
2025-01-06T04:44:56.578001Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 23v0
2025-01-06T04:44:56.578036Z DEBUG bevy_ecs::world::entity_ref: Despawning entity 32v0
```

2025-01-06 04:48 UTC, koonpeng commented on src/diagram.rs
> +pub type NodeId = String;
ca56917

2025-01-06 05:23 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
This whole problem would be extremely easy with the `min_specialization` language feature, but there's no telling how much longer before that features is available in stable Rust, so sadly yeah we're going to need to figure out the least objectionable set of trade-offs to solve this problem.

Using `derive` is worth considering, but derive macros are unable to infer traits of the structs and enums that they are used on (nor on the fields of those structs and enums), because derive macros run before trait resolution is performed. That puts some significant limits on how much we can automate with macros. And then accounting for how it will interfere with users' ability to send and receive data types that are independent of `bevy_impulse`, I find it hard to justify that approach.

> group ops together ... `ForkCloneAndUnzip<NotSupported, DefaultImpl>`

I don't think this will meaningfully reduce the overall complexity of the generics, it would just shift it deeper and probably make the overall setup harder to understand.

> Having some operations like fork clone opt-out, similar to serialization. For now it's just fork clone and fork result I'm considering but with the above design, I find it less ergonomic that this change will require refactoring instead of just flipping a switch.

In the setup that I'm proposing, opt-out operations would go into `OpacityNodeBuilder`. If we anticipate we'll want to add more opt-out operations in the future then we can consider changing the term "opacity" to something else, e.g.:

```rust
pub struct DefaultOps<Deserializer, Serializer, Cloneable> {
    ...
}

impl<S, C> DefaultOps<DefaultDeserializer, S, C> {
    pub fn no_request_deserialize(self) -> DefaultOps<NotSupported, S, C> { ... }
}

impl NodeRegistry {
    pub fn opt_out(&mut self) -> DefaultOps<DefaultDeserializer, DefaultSerializer, DefaultClone> {
        ...
    }

    pub fn register_node_builder< ... >( ... ) -> RegistrationBuilder<Request, Response, Streams>
    where
        ...
    {
        self.opt_out().register_node_builder()
    }
```

With that approach, we would only need to add new generics for `DefaultOps`, which I think would happen very rarely since the vast majority of operations are only applicable to specific data types. If we make `fork_clone` a default operation then we're still capping out our generic arguments at 3 per struct even if we keep adding non-default operations in the future.

2025-01-06 05:26 UTC, koonpeng commented on src/diagram/join.rs
> +    let first_type = outputs[0].type_id;
e3e1fb7801705010624e60823a35a049cad496a1

2025-01-06 05:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                if target.in_edges.is_empty() {
This seems redundant with the previous check

2025-01-06 05:50 UTC, mxgrey commented on src/diagram/join.rs
> +            // so nodes need to take a request of `JoinOutput<Box<dyn Any>>`.
This might be too cumbersome for users in many cases.

What if we do:

```
{
    "type": "join",
    "next": "foo",
    "serialize": true
}
```

so users can decide within the diagram to send a serialized version of the data to the next node. I think it'll be much less troublesome for users to create nodes that support deserializing than nodes that can only connect to `JoinOutput<T>`.

2025-01-06 05:50 UTC, koonpeng commented on src/diagram/workflow_builder.rs
> +                if target.in_edges.is_empty() {
08631b4c15a8dded54452e4783d0bfb80dea83f0 oops, copy paste error

2025-01-06 09:53 UTC, koonpeng commented on diagram.schema.json
> +                "start"
6a20ef52d1990be529b1d2149316a91c361fab04

2025-01-06 16:24 UTC, mxgrey commented on src/diagram.rs
> +    version: u32,
I like the idea of a built-in version number, but I think we should use a [`SemVer`](https://github.com/open-rmf/rmf_site/blob/main/rmf_site_format/src/semver.rs#L38) so we can distinguish between forward-compatible and incompatible format changes.

I wrote that `SemVer` class several years ago so it may be worth checking if there's a small crate out in the ecosystem that implements the same concept.

2025-01-06 16:27 UTC, mxgrey commented on src/diagram.rs
> +    version: u32,
This crate may be worth considering: 

https://docs.rs/serde-semver/latest/serde_semver/

The only thing I don't like is it doesn't seem to let us inspect the actual version number that was present in the serialized data.

2025-01-07 03:06 UTC, koonpeng commented on src/diagram.rs
> +    version: u32,
9a231e726654ac73f9e9dfb7c5b50d89fee5f01a

Personally I don't think semver is needed, but it wouldn't hurt also so I changed it.

2025-01-07 03:51 UTC, koonpeng commented on src/diagram/join.rs
> +            // so nodes need to take a request of `JoinOutput<Box<dyn Any>>`.
41a123b9e1d340ebfea021b82013237ce8ab095f

2025-01-07 04:59 UTC, mxgrey commented on src/diagram/join.rs
> +            // so nodes need to take a request of `JoinOutput<Box<dyn Any>>`.
What would you think of the `serialize` option being true by default? I suspect that's what users will want more often than not since the non-serialized version requires them to expect a specific size of `SmallVec`.

2025-01-07 06:06 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
I just thought of a tricky issue with join...

In many cases the order of the inputs going into the join will matter. This is especially the case when the node after the join is expecting a heterogeneous mix. For example if the node after the join expects an input of `(Pose, Velocity)` then it will fail to deserialize if we pass along a `Value::Array([velocity, pose])`.

I think we need to introduce a new field to the `join` operation:

```json
{
    "type": "join",
    "inputs": ["foo", "bar"],
    "next": "baz"
}
```

We'll use the `inputs` field to determine the order that the inputs are arranged in the output. If there's ever a mismatch between the values in `inputs` and the `next` value of one of those inputs, then that should be treated as an error.

This will also be important in the future when we add support for buffers. Buffers are the real inputs for a `join` operation (`join` can take in a bunch of `Output`s, but it actually changes them into buffers before joining them). Buffers won't be able to specify a `next` at all, so the `join` operation will need to be told which buffers to pull from, and we can do that with the `inputs` field.

2025-01-07 06:27 UTC, koonpeng commented on src/diagram/join.rs
> +            // so nodes need to take a request of `JoinOutput<Box<dyn Any>>`.
I think it mostly depends on the type of app and the type of user. The end user (the user of the app that uses bevy_impulse diagram) would probably not care about perf, defaulting to serialize would make writing diagrams easier. The users of bevy_impulse (the devs of the app) might not want to end users to serialize, but perhaps defaulting to serialize is one way to push them to have their own "join" node specialized for the data they are handling.

2025-01-07 06:31 UTC, koonpeng commented on src/diagram/join.rs
> +            // so nodes need to take a request of `JoinOutput<Box<dyn Any>>`.
922db287189996ee529beb13bf38c4f901b01141

2025-01-07 06:42 UTC, koonpeng commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
I'm not sure I understand this, I assume the items in the `inputs` array are referring to another operation id? But I'm not sure how we can use that to make the output of join stable.

2025-01-07 06:49 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
Correct, the items in `inputs` would be the IDs of other operations (which would also include the names of buffers). The output of join would be stable because we would always arrange the values in the array in the order of the names specified by `inputs`. So if we have `"inputs": ["pose", "velocity"]` where `pose` is outputting a `Pose` and `velocity` is outputting a `Velocity` then we can be confident that the output of `join` will always be a `Value::Array([Pose, Velocity])` which can then be deserialized to a `(Pose, Velocity)`.

Remember that the `join` operation will wait until at least one value of each output is available and then grab the oldest of each to produce the output of the `join`. We just need to make sure that when it grabs the oldest of each, it will arrange them in the array in the order that's expected by the next operation.

2025-01-07 07:33 UTC, koonpeng commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
064ec4e84db4e23f9f3984c8f1c19f9f23d75b57

I stablized the order of the outputs passed to `join_vec`, it seems to work for `test_serialize_and_join` but `test_join` is still unstable, could it be due to the extra nodes in `test_join`?

2025-01-07 09:31 UTC, mxgrey commented on src/diagram/join.rs
> +    pub(super) order: Vec<SourceOperation>,
I understand why you named this `order`, but it will make more sense for it to be named `inputs` or `sources` once we add support for buffers. Buffers won't have a concept of `next`, so this field will be the only place where we will see a connection between a `buffer` and a `join`. At that point it's describing more than just an order; it's describing what its inputs are.

2025-01-07 13:04 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
This one was quite a doozy to figure out. I did a bunch of debug tracing all the way down into the weeds of the `join_vec` implementation trying to find where the outputs could be getting crossed, only to find that it was always working perfectly.

Eventually I tracked the problem down to [this code for the split operation](https://github.com/open-rmf/bevy_impulse/blob/632dfc236f8f57307586cb3684d1815494da534f/src/diagram/workflow_builder.rs#L431-L438). The split outputs are being generated correctly [here](https://github.com/open-rmf/bevy_impulse/blob/632dfc236f8f57307586cb3684d1815494da534f/src/diagram/workflow_builder.rs#L418) as a map from `NextOperation` to the relevant `Output` from the split. However on [this line](https://github.com/open-rmf/bevy_impulse/blob/632dfc236f8f57307586cb3684d1815494da534f/src/diagram/workflow_builder.rs#L435) the `NextOperation` is discarded and replaced with an arbitrary entry from `target.out_edges`.

Changing that block to

```rust
for e in &target.out_edges {
    let out_edge = edges.get_mut(e).unwrap();
    let output = outputs.outputs.remove(out_edge.target).unwrap();
    out_edge.state = EdgeState::Ready { output, origin };
}
```

and making `outputs` mutable fixed the stability issue. Essentially the split operation was randomly pairing each of its outputs to any operation that was connected to it instead of the one that the user specifically asked for.

It's a good thing we had these tests or else this could've easily been missed. I might recommend making a smoke test that does a big split (maybe ~10 values) followed by a big join of all those values, and make sure the final result has every element in the correct location. A really good smoke test would rerun the test numerous times with a randomized set of operation names, since the hashmaps used in the implementation could scramble the orderings based on the name values.

2025-01-08 01:51 UTC, koonpeng commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
Thanks for helping to figure this out! Yeah, I can see how split causes the ordering to go wrong.

2025-01-08 02:34 UTC, koonpeng commented on src/diagram/workflow_builder.rs
> +            let outputs: Vec<DynOutput> = target
632dfc236f8f57307586cb3684d1815494da534f...e826741a0de362e1b34c58dea3c4cfa937e50fcb

2025-01-08 05:37 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        name: &'static str,
To be more specific, it is the node builder's name. Putting a label in the diagram would be more suitable for the operation's name. I am thinking of a scenario where you have a list of node builders available, and you drag one of them to the canvas to add it into a diagram, this is one way that the name would be used.

2025-01-08 05:57 UTC, koonpeng commented on diagram.schema.json
> +          "oneOf": [
One reason why I avoided this is because json parsers/interpreters can be finicky. Some of them may allow you to access an array via a key e.g. `arr["1"]`. It does not exactly conflict with dual key-seq support, but it does make things confusing.

```json
{
    "type": "split",
    // an array is actually passed in
    "keys": {
        "1": "node_connected_to_a", // refers to the 2nd item
    },
    "sequential": [
        "first_node", // first item
        "second_node" // third(?) item
    ]
}
```

I wonder in practice how useful dual key-seq would be compared to key + remaining to get the other items. key + remaining does have a downside that you can't grab a subset of the unpicked keys (possible if you connect the output of remaining to another split), but if the input is a `std::HashMap`, the order of the seq outputs would not be stable.

2025-01-08 06:11 UTC, mxgrey commented on diagram.schema.json
> +          "oneOf": [
I agree that it would be strange to see situations where people mix both keyed and sequential connections. But since there is no technical reason to prohibit it, and there's no additional difficulty in us supporting it, I would rather leave it up to users to decide if/when simultaneous access to both may be useful for them.

Also I'm thinking we should name the field `keyed` instead of `keys` since I think `keyed` as an adjective aligns better with the adjective `sequential`.

2025-01-08 06:14 UTC, mxgrey commented on diagram.schema.json
> +          "oneOf": [
FWIW when it comes to RMF workflows and especially task descriptions, I'm planning on adding an opinionated layer between `bevy_impulse` and the RMF user. That additional layer would add some guard rails around how tasks and RMF workflows are built.

Meanwhile for `bevy_impulse` we should try to keep it as general purpose (unopinionated) as possible so it can be used beyond what we're targeting for RMF.

2025-01-08 09:43 UTC, mxgrey requested changes
This review is primarily an audit of the use of `.unwrap()` inside the critical path.

It's imperative that we bring the risk of crashing/aborting/panicking as close to zero as possible, or else we undermine the crash-free exception-free selling points of Rust.

There will certainly be cases where we can guarantee that `.unwrap()` is perfectly safe, and in those places we should add clear documentation to explain how we know this.

But in general we should prefer to return `Err` results if we aren't positively 100% certain that the unwrap will not panic.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/join.rs
> +        .map_block(|o| serde_json::to_value(o).unwrap())
What are the conditions in which this `.unwrap()` might panic? We should either document a rationale for why a panic is impossible, or else we should use `.cancel_on_err()` here instead of `.unwrap()`.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram.rs
> +    let ver_req = semver::VersionReq::parse(SUPPORTED_DIAGRAM_VERSION).unwrap();
This seems like it should return an error rather than unwrapping. If we can guarantee that the unwrap won't panic then we need to include a comment providing the rationale.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/split_serialized.rs
> +                            let position = JsonPosition::ObjectField(key.specific().unwrap());
I know I wrote this line, but I had already forgotten what the safety rationale is for being able to use `.unwrap()` here. We should add a line of documentation like

```rust
// SAFETY: This key was initialized as MapSplitKey::Specific earlier in the function and is immutable,
// so this method is guaranteed to return Some
```

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/split_serialized.rs
> +                            let position = JsonPosition::ObjectField(key.specific().unwrap());
We should add the same safety documentation here.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            vertices.get_mut(&op_id).unwrap().in_edges.push(0);
We should either provide a rationale for why this unwrap cannot panic or this case should be covered as a `DiagramError`.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +        let edge = edges.remove(&edge_id).unwrap();
Either provide a safety rationale or return a `DiagramError`.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                    let edge = edges.remove(e).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            let out_edge = edges.get_mut(&target.out_edges[0]).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +    let edge = edges.remove(&edge_id).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                    let out_edge = edges.get_mut(e).unwrap();
Safety rationale or `DiagramError`

Also I recommend using conventional for-loops instead of `for_each` if you don't have a very long chain leading up to it. Conventional for-loops make error handling more ergonomic.

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                    let out_edge = edges.get_mut(e).unwrap();
Safety rationale or `DiagramError`

Also consider a conventional for-loop

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                let out_edge = edges.get_mut(&target.out_edges[0]).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                let out_edge = edges.get_mut(&target.out_edges[1]).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                Some(target.out_edges.last().unwrap())
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                let out_edge = edges.get_mut(e).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                let output = outputs.outputs.remove(out_edge.target).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +                let out_edge = edges.get_mut(remaining_edge_id).unwrap();
Safety rationale or `DiagramError`

2025-01-08 09:43 UTC, mxgrey commented on src/diagram/workflow_builder.rs
> +            let out_edge = edges.get_mut(&target.out_edges[0]).unwrap();
Safety rationale or `DiagramError`

2025-01-08 11:22 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        name: &'static str,
> Do we expect that to commonly be different from the id?

That would depends on several factors. Right now `id` is just a string with no constraints, so it is very tempting to make that same as `name`, but I believe there are reasons to consider constraining it. Whether user needs `name` would also depends on how they want to manage ids, if they use a UUID string for ids, then they would almost certainly need `name`. A potential use case for doing something like that is the scenario we discussed in the choice of `&'static str`. If they are storing builders in dbs, or generating builders at run time, then there is a good reason to use something like UUIDs or hashes for ids.

An alternative is to use a `label: HashMap<String, String>` to store extra data, but I think `name` is fundamental enough that it should always be required (if we consider frontend as a first class feature).

2025-01-08 11:46 UTC, koonpeng commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
While trying to change this, I realized that it will require a pretty large refactor. There are also some things that I will need more time to implement, particularly `DefaultOps::register_node_builder()` needs to pass the serializers etc to `RegistrationBuilder`, can be easily done by adding a generic param to `RegistrationBuilder`, but then we wouldn't really need `opt_out` anymore in that case, we can do something like

```rust
struct RegistrationBuilder<Opacity, Request, Response, Streams> {
  ...
  // these are now needed because we no longer "stores" the impls in generic params.
  fork_clone_impl: Option<Box<dyn DynForkClone>>,
  ...
}

impl<...> RegistrationBuilder<...> {
  fn opaque_request(...) -> RegistrationBuilder<OpacityImpl<Opaque, Default>, ...> {
      ...
  }
}
```

I'm also still not convinced that we should drop the idea of using derives. Derive could potentially allow us to remove the need to opt out/in many operations like unzip, fork result and split, every node can then automatically register impls for those operations. That leaves only serialization and fork clone that still needs manual control. tbh I'm still not certain if that is possible but I do have some ideas and I think it is worth exploring.

2025-01-08 13:06 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
> Derive could potentially allow us to remove the need to opt out/in many operations like unzip, fork result and split

We can't apply `derive` to any `Result<T, E>` so that immediately rules out its usefulness for `fork_result`. I think we should shelf the derive idea for this initial implementation. There are too many jagged edges.

2025-01-08 13:12 UTC, mxgrey commented on src/diagram/node_registry.rs
> +        name: &'static str,
Understood. I think we should use the `NodeBuilderOptions` pattern for the sake of forwards API compatibility. I think having an equivalent `id` and `name` will be common enough that users will appreciate being able to just define one of them.

```rust
#[non_exhaustive]
pub struct NodeBuilderOptions {
    pub id: String,
    pub name: Option<String>,
}
```

Then we can add more fields to `NodeBuilderOptions` if we ever want to add more options for the node builders.

2025-01-08 14:22 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
> needs to pass the serializers etc to RegistrationBuilder

I looked into this more. I see that `SerializeImpl` is used by `SplitImpl` and `UnzipImpl`, so I take it that's why you say that `RegistrationBuilder` needs the serializer. I still think `<Opacity, Request, Response, Streams>` is preferable to the six generic arguments that it currently needs, especially since that number would be prone to grow if we add more operations.

Another option would be to offer variations for `split` and `unzip` that don't require `Opacity`:

```rust
fn with_split(self) -> RegistrationBuilder<...> { ... }
fn with_split_unserializable(self) -> RegistrationBuilder<...> { ... }
```

The first one would require `Response::Item` to be serializable whereas the second one wouldn't. In principle this is more rigorous than the current approach for the (admittedly very weird) case where `Response` is not serializable but `Response::Item` is serializable or vice-versa. With this approach we could just have `RegistrationBuilder<Request, Response, Streams>`.

2025-01-09 03:45 UTC, koonpeng commented on src/diagram/node_registry.rs
> +        name: &'static str,
ce17e0d6e5c013bb09dbe7b76829fcc3ff49505c

2025-01-09 03:51 UTC, koonpeng commented on src/diagram/join.rs
> +        .map_block(|o| serde_json::to_value(o).unwrap())
Technically this will never fail because we are converting a (Small)Vec of Value to a Value. But I made it `cancel_on_err` just in case.

2025-01-09 04:55 UTC, koonpeng commented
It is hard to explain how the `unwraps` in `workflow_builder.rs` are safe. We usually access `edges` with a key that comes from `vertices` and both are built using the same data, so in theory it would never panic. But we do modify `edges` while building the workflow so the preconditions because very complex.

I added a `UnknownDiagramError`, for these unwraps, it captures the backtrace to help debug if it ever happens.

2025-01-09 04:59 UTC, mxgrey commented on src/diagram.rs
> +type DefinitelyNotBacktrace = backtrace::Backtrace;
Just making sure I understand, without this type alias the code will fail to compile on nightly? I assume it should compile without any issue on stable, right?

Also while this name is honestly very funny, we should rename it to something like `BacktraceAlias`.

2025-01-09 05:04 UTC, koonpeng commented on src/diagram.rs
> +type DefinitelyNotBacktrace = backtrace::Backtrace;
It's the other way round, it won't compile without this alias, `thiserror` only supports backtrace on nightly.

2025-01-09 05:17 UTC, mxgrey commented on src/diagram.rs
> +type DefinitelyNotBacktrace = backtrace::Backtrace;
I'm a little bit concerned about only including the file and line location since users won't always know which version of the source code to compare against. What if we add a `&str` message inside of `unknown_diagram_error!(~)` similar to `.expect(~)` to help narrow down which line had an error?

2025-01-09 05:18 UTC, mxgrey commented on src/diagram.rs
> +type DefinitelyNotBacktrace = backtrace::Backtrace;
On the other hand if we're only using this error type for truly unexpected errors, then I don't mind leaving it as-is for now and we can see if any of these errors actually occurs after exercising the feature for a while.

2025-01-09 05:48 UTC, koonpeng commented on diagram.schema.json
> +          "oneOf": [
046f81f99ed7a6b8a7e9143ebc951b5c4ad70336

2025-01-09 07:02 UTC, mxgrey commented on src/diagram/node_registry.rs
> +    ) -> RegistrationBuilder<
Resolved by #45

2025-01-09 07:19 UTC, mxgrey approved these changes
Thanks for all the rigorous iterating @koonpeng 

I'm super happy with how this capability turned out. The JSON syntax is very clean and intuitive without limiting what can be done with it. The fact that the schema can be generated from native Rust structs is even better.

We still have plenty more operations to add, but this initial set is already very powerful, and most importantly it sets a strong foundation for us to continue building off of.

2025-01-09 07:33 UTC, merged